-- Initialize exchange rates for USD
INSERT INTO EXCHANGE_RATES (base_currency, target_currency, rate, last_updated)
VALUES 
('USD', 'EUR', 0.92, CURRENT_TIMESTAMP),
('USD', 'GBP', 0.78, CURRENT_TIMESTAMP),
('USD', 'PLN', 3.95, CURRENT_TIMESTAMP),
('USD', 'JPY', 150.25, CURRENT_TIMESTAMP),
('USD', 'CAD', 1.35, CURRENT_TIMESTAMP),
('USD', 'AUD', 1.48, CURRENT_TIMESTAMP),
('USD', 'CHF', 0.90, CURRENT_TIMESTAMP),
('USD', 'CNY', 7.23, CURRENT_TIMESTAMP),
('USD', 'INR', 83.45, CURRENT_TIMESTAMP);

-- Initialize exchange rates for EUR
INSERT INTO EXCHANGE_RATES (base_currency, target_currency, rate, last_updated)
VALUES 
('EUR', 'USD', 1.09, CURRENT_TIMESTAMP),
('EUR', 'GBP', 0.85, CURRENT_TIMESTAMP),
('EUR', 'PLN', 4.30, CURRENT_TIMESTAMP),
('EUR', 'JPY', 163.50, CURRENT_TIMESTAMP),
('EUR', 'CAD', 1.47, CURRENT_TIMESTAMP),
('EUR', 'AUD', 1.61, CURRENT_TIMESTAMP),
('EUR', 'CHF', 0.98, CURRENT_TIMESTAMP),
('EUR', 'CNY', 7.87, CURRENT_TIMESTAMP),
('EUR', 'INR', 90.85, CURRENT_TIMESTAMP);
